### ISSUE TITLE
💄 Suggestion - Home Page - Odd link

### ISSUE THREAD

**Issue by SamBWagner** [BrookJeynes/brookjeynes.dev#6]
# Odd Link

There's a link to the page at the end of the page. Idk seems weird.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/66365977/235339866-80f6430b-143d-44a8-b0f6-68c3dd2d11fe.png">

**Figure: Home Page: Odd Link**

**Comment by BrookJeynes** [comment]
@SamBWagner it's a stylistic choice

**Comment by SamBWagner** [comment]
Totally fair. Ty for the reply 👍
